More LHCb python3
ganga-devs/ganga pull request #1489
Opened 2019-07-08 14:04 UTC by mesmith75

2019-07-10 12:18 UTC, alexanderrichards commented
@mesmith75 ready to merge?

2019-07-16 17:25 UTC, mesmith75 commented
So I *think* this solves the monitoring issues.

2019-07-17 09:10 UTC, mesmith75 commented
@alexanderrichards I think this can be merged now

2019-07-17 10:16 UTC, alexanderrichards requested changes
Thanks for doing this @mesmith75 and good spot on the FunctionInput namedtuple rich comparison operators, I forgot about that.

2019-07-17 10:16 UTC, alexanderrichards commented on ganga/GangaCore/GPIDev/Adapters/IBackend.py
> +                                print("added to uqueueue")
Can we lose the prints?

2019-07-17 10:16 UTC, alexanderrichards commented on ganga/GangaCore/GPIDev/Adapters/IBackend.py
> +                        logger.error("arse Monitoring Error: %s" % err)
:wink:

2019-07-17 10:18 UTC, alexanderrichards approved these changes

2019-07-17 10:26 UTC, merged