Add deprecation warning for old Ganga
ganga-devs/ganga pull request #1506
Opened 2019-10-22 08:21 UTC by mesmith75

Add a deprecation warning to the last Ganga 7 release.

2019-10-22 08:44 UTC, egede requested changes
Rather than leaving this a crap in the code, can you just enter it in without the if statement, make the release and then remove it again as part of the next release.

2019-10-22 08:49 UTC, mesmith75 commented
That makes more sense

2019-10-22 09:22 UTC, alexanderrichards approved these changes

2019-10-23 08:58 UTC, egede approved these changes

2019-10-23 08:59 UTC, merged