Update LHCbDataset
ganga-devs/ganga pull request #1559
Opened 2020-01-15 14:28 UTC by mesmith75

For use with `LHCbCompressedDataset`. This updates the `__init__` to take a compressed dataset and also the comparisons.

As the two types reference each other here I had to put the `import` statements at specific points rather than at the top.

2020-01-15 14:41 UTC, alexanderrichards requested changes

2020-01-15 14:41 UTC, alexanderrichards commented on ganga/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py
> +        from GangaLHCb.Lib.LHCbDataset.LHCbCompressedDataset import LHCbCompressedDataset
Can we move imports to the top of the file?

2020-01-15 14:41 UTC, alexanderrichards commented on ganga/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py
> +        from GangaLHCb.Lib.LHCbDataset.LHCbCompressedDataset import LHCbCompressedDataset
ditto

2020-01-15 14:41 UTC, alexanderrichards commented on ganga/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py
> +        from GangaLHCb.Lib.LHCbDataset.LHCbCompressedDataset import LHCbCompressedDataset
ditto

2020-01-15 22:18 UTC, egede submitted a review, later dismissed

2020-01-17 13:32 UTC, alexanderrichards approved these changes

2020-01-17 14:16 UTC, merged