Fix missing python3 upgrade
ganga-devs/ganga pull request #1585
Opened 2020-02-21 15:18 UTC by mesmith75

One slipped through.

2020-02-21 15:24 UTC, alexanderrichards requested changes
One slipping through is not so bad but surprised given it's location it was missed. I assume you saw this while answering my question about importing little ganga

2020-02-21 15:24 UTC, alexanderrichards commented on ganga/ganga/__init__.py
> +    raise(GangaException(x), None, sys.exc_info()[2])
This is probably more Pythonicly written in Python3 as:
```suggestion
    raise GangaException.with_traceback(sys.exc_info()[2])
```

2020-02-21 15:29 UTC, alexanderrichards approved these changes

2020-02-24 00:33 UTC, egede approved these changes
Thanks. Was just about to file a bug report on this.

2020-02-24 10:04 UTC, merged