Don't download inputdata for files with accessURL
ganga-devs/ganga pull request #1701
Opened 2020-06-22 15:41 UTC by mesmith75

Fixes #1698 .

This checks if a file from the inputdata has an accessURL . If it does then the inputdata won't be downloaded.

2020-06-24 06:03 UTC, egede requested changes
I am a bit confused about what problem you are solving here. Is it about downloading to the worker node or about downloading after the job has finished?

2020-06-24 06:03 UTC, egede commented on ganga/GangaCore/GPIDev/Lib/File/OutputFileManager.py
> +                        inputfiles_list.append(_f)
```python
if not _f.accessURL():
    inputfiles_list.append(_f)
```
seems shorter and clearer

2020-06-24 06:03 UTC, egede commented on ganga/GangaCore/GPIDev/Lib/File/OutputFileManager.py
> +                        inputfiles_list.append(_f)
as above

2020-06-24 09:38 UTC, mesmith75 commented
This solves #1698 . When running local or interactive jobs ganga is downloading remote inputdata to the WN. It doesn't make sense because the `data.py` file we create uses the remote access so we are filling up the tmp directory with massive data files for no reason.

2020-06-28 22:48 UTC, egede approved these changes

2020-06-29 08:20 UTC, merged