runMonitoring take more types addition
ganga-devs/ganga pull request #2390
Opened 2024-10-29 19:07 UTC by saadkhi

The issue solved was to make `runMonitoring` accept different job inputs—specifically, an integer (job ID), a list of integers (job IDs), and a job object—in addition to the original job slice format. This increases flexibility in specifying jobs for monitoring.

fixed #2380

2024-10-29 22:14 UTC, mesmith75 commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> +    def runMonitoring(self, steps, timeout, jobs=None):
We don't want to change these arguments

2024-10-29 22:15 UTC, mesmith75 commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> -          This method is meant to be used in Ganga scripts to request monitoring on demand.
Could you leave this part of the docstring?

2024-10-29 22:17 UTC, mesmith75 commented
You seem to have included your virtualenv in the commit - could you remove that?

You also seem to have touched a lot of things that are best left alone. Also I think some issues have occurred with indenting/whitespace etc. Could you try and tidy that up?

The issue only needs some pretty minimal changes so could you try and tidy this up to only include the minimal adjustments necessary?

2024-10-30 19:29 UTC, saadkhi commented
Yes, I will make changes and update soon.

2024-10-31 04:44 UTC, egede requested changes

2024-10-31 04:44 UTC, egede commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> +            elif isinstance(jobs, jobs):
This seems to make no sense to me. Is there an overload of symbols here (between the argument jobs to the function and the global jobs object?

2024-10-31 04:44 UTC, egede commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> +            elif isinstance(jobs, list):
Should a list of job objects be allowed as well? Like
```
j1 = Job()
j2 = Job()
runMonitoring([j1,j2])
```

2024-11-04 09:49 UTC, egede commented
There is something odd going on with the testing here. Not sure what as it seems unrelated to the code changes that you have made.

2024-11-04 09:52 UTC, alexanderrichards commented
@saadkhi I think for the failure of the autopep8 test, when you created the pull request did you click the checkbox to allow upstream developers to make changes to your branch? My best guess at the moment for whats happening here is it's trying to create the autopep8 branch to pull against *your* branch `Enh_int`

2024-11-04 09:58 UTC, egede commented
@saadkhi Take a look at the GangaCore Integration tests. There are 3 errors there that relate to the code that you modified. Please take a look first yourself and then ask for help if you can't figure out what is wrong. 

Check the [full details](https://github.com/ganga-devs/ganga/actions/runs/11601147069/job/32466884666?pr=2390). Extract below.

```
FAILED ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py::TestMonitoring::test_b_EnableMonitoring - TypeError: AsyncMonitoringService.runMonitoring() got an unexpected keyword argument 'steps'
FAILED ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py::TestMonitoring::test_g_runMonitoring_withJobIDList - TypeError: AsyncMonitoringService.runMonitoring() got an unexpected keyword argument 'steps'
FAILED ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py::TestMonitoring::test_h_runMonitoring_withJobObject - TypeError: AsyncMonitoringService.runMonitoring() got an unexpected keyword argument 'steps'
```

2024-11-04 12:34 UTC, saadkhi commented
> @saadkhi I think for the failure of the autopep8 test, when you created the pull request did you click the checkbox to allow upstream developers to make changes to your branch? My best guess at the moment for whats happening here is it's trying to create the autopep8 branch to pull against _your_ branch `Enh_int`

I'm not sure about it, let me check and fix what is going wrong with it.

2024-11-04 12:36 UTC, saadkhi commented
> @saadkhi Take a look at the GangaCore Integration tests. There are 3 errors there that relate to the code that you modified. Please take a look first yourself and then ask for help if you can't figure out what is wrong.
> 
> Check the [full details](https://github.com/ganga-devs/ganga/actions/runs/11601147069/job/32466884666?pr=2390). Extract below.
> 
> ```
> FAILED ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py::TestMonitoring::test_b_EnableMonitoring - TypeError: AsyncMonitoringService.runMonitoring() got an unexpected keyword argument 'steps'
> FAILED ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py::TestMonitoring::test_g_runMonitoring_withJobIDList - TypeError: AsyncMonitoringService.runMonitoring() got an unexpected keyword argument 'steps'
> FAILED ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py::TestMonitoring::test_h_runMonitoring_withJobObject - TypeError: AsyncMonitoringService.runMonitoring() got an unexpected keyword argument 'steps'
> ```

yes, @egede I'm working on it to figure out why these test cases get failling.

2024-11-04 18:33 UTC, saadkhi commented
> @saadkhi I think for the failure of the autopep8 test, when you created the pull request did you click the checkbox to allow upstream developers to make changes to your branch? My best guess at the moment for whats happening here is it's trying to create the autopep8 branch to pull against _your_ branch `Enh_int`

I’m having trouble understanding what autopep8 is and how it applies to my pull request. Could you please explain it, or if possible, arrange a meeting sometime this week to discuss?

2024-11-05 12:05 UTC, alexanderrichards commented
> I’m having trouble understanding what autopep8 is and how it applies to my pull request. Could you please explain it, or if possible, arrange a meeting sometime this week to discuss?

so PEP8 is the python style guidelines for coding. Autopep8 is a tool that when run over a codebase will convert all files to the PEP8 standard. As part of our CI/CD pipeline we run an action that automatically runs this autopep8 tool over the files that you have modified and creates a new branch/pull request with the changes necessary to meet the PEP8 standard.

Hopefully that is clear. If not, I can have a separate conversation with you or alternatively you could probably join our Monday morning meeting.

2024-11-09 20:45 UTC, saadkhi commented
> > I’m having trouble understanding what autopep8 is and how it applies to my pull request. Could you please explain it, or if possible, arrange a meeting sometime this week to discuss?
> 
> so PEP8 is the python style guidelines for coding. Autopep8 is a tool that when run over a codebase will convert all files to the PEP8 standard. As part of our CI/CD pipeline we run an action that automatically runs this autopep8 tool over the files that you have modified and creates a new branch/pull request with the changes necessary to meet the PEP8 standard.
> 
> Hopefully that is clear. If not, I can have a separate conversation with you or alternatively you could probably join our Monday morning (UK time) meeting.

Okay, I'll join the meeting and then will solve the autopep8 issue after meeting as soon as possible.

2024-11-11 09:13 UTC, alexanderrichards commented
> Okay, I'll join the meeting and then will solve the autopep8 issue after meeting as soon as possible.

👍🏻 The meeting is in 17 mins. Do you have the connection details? If you are on the mattermost channel there is a link at the top

2024-11-11 10:41 UTC, mesmith75 commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> +            self.makeUpdateJobStatusFunction(jobSlice=m_jobs)
Why has the order changed? I think we want to grab the lock first still

2024-11-11 10:41 UTC, mesmith75 commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> -            # set how many steps to run
Why are we losing all these comments?

2024-11-11 10:41 UTC, mesmith75 commented on ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py
> -        self.assertNotEqual(jobs(0).status, 'submitted')
I don't think we want to change this test.

2024-11-11 18:29 UTC, saadkhi commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> +            self.makeUpdateJobStatusFunction(jobSlice=m_jobs)
What I have to do, kindly explain. I’ll update it soon.

2024-11-12 10:35 UTC, mesmith75 commented on ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py
> +            self.makeUpdateJobStatusFunction(jobSlice=m_jobs)
You have moved this entire chunk of code - I think it needs to go back to its original location

2024-11-12 10:41 UTC, egede reviewed
There is something really fishy here. 

It turns out that we have two `runMonitoring` functions in the codebase. One in [MonitoringService.py](https://github.com/ganga-devs/ganga/blob/35e3bcf552519c8aae5f36c8a5d6cef49255f68d/ganga/GangaCore/Core/MonitoringComponent/MonitoringService.py#L235) and one in [Local_GangaMC_Service.py](https://github.com/ganga-devs/ganga/blob/35e3bcf552519c8aae5f36c8a5d6cef49255f68d/ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py#L709). 

If I force the runMonitoring method that is edited in this PR to always return False, then the tests are still passing! My conclusion is that the code is never called.

2024-11-12 10:44 UTC, alexanderrichards commented on ganga/GangaCore/test/GPI/Monitoring/TestMonitoring.py
> -        self.assertNotEqual(jobs(0).status, 'submitted')
I agree, we shouldn't be changing the testing files at all (except to add new tests)

2024-11-12 11:24 UTC, egede commented
So looking in the [coverage of the testing](https://github.com/ganga-devs/ganga/actions/runs/11670321659/job/32531509439?pr=2390#step:5:473) I indeed see that the code that you have implemented is never executed. So in fact the entire `runMonitoring` function in [Local_GangaMC_Service.py](https://github.com/ganga-devs/ganga/blob/35e3bcf552519c8aae5f36c8a5d6cef49255f68d/ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py#L709) can be removed.

2024-11-12 11:25 UTC, egede commented
So the real question now is what the new test files are actually testing. At the moment they just look for `runMonitoring` returning `True`, but they should be extended to see if the jobs in question are actually monitored (and others not). It could be the argument is just ignored. Sorry @saadkhi but this is turning more complicated that we realised and we probably gave you the wrong advise to begin with.

2024-11-12 16:03 UTC, saadkhi commented
> So the real question now is what the new test files are actually testing. At the moment they just look for `runMonitoring` returning `True`, but they should be extended to see if the jobs in question are actually monitored (and others not). It could be the argument is just ignored. Sorry @saadkhi but this is turning more complicated that we realised and we probably gave you the wrong advise to begin with.


Hi @egede, thank you for your guidance. Initially, I created the test cases based on the `Local_GangaMC_Service` implementation in [Ganga](https://github.com/ganga-devs/ganga/blob/35e3bcf552519c8aae5f36c8a5d6cef49255f68d/ganga/GangaCore/Core/MonitoringComponent/Local_GangaMC_Service.py#L709), but encountered errors during your testing process. After that, I noticed the `runMonitoring` functionality in the [MonitoringService](https://github.com/ganga-devs/ganga/blob/35e3bcf552519c8aae5f36c8a5d6cef49255f68d/ganga/GangaCore/Core/MonitoringComponent/MonitoringService.py#L235) and adjusted the test cases accordingly. 

I’ll continue to explore the Ganga project and improve my contributions alongside the team. I appreciate your support and feedback. Thank you again!

2024-12-09 09:47 UTC, closed without merging

2024-12-09 09:47 UTC, mesmith75 commented
I think this went a bit off-piste, so closing.